version: '3.9'

services:
  nginx:
    container_name: social-nginx
    image: nginx:1.25.2-alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.dev:/etc/nginx/conf.d
      - ../static:/opt/services/static
      - ../media:/opt/services/media
    networks:
      - nginx_network