version: '3.8'
services:
  backend: &backend
    container_name: social_back
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ..:/opt/services
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
      --no-input && python manage.py runserver 0.0.0.0:8000"
    networks:
      - main_network
      - nginx_network

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ../storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main_network
#    env_file:
#      - ../.env

  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    ports:
    - "6379:6379"
    networks:
      - main_network
    env_file:
      - ../.env

networks:
  main_network:
    driver: bridge
  nginx_network:
    driver: bridge
