# Generated by Django 5.0.4 on 2024-06-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], default='Другой', max_length=7),
        ),
    ]
