# Generated by Django 5.0.4 on 2024-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_education_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preffered_gender',
            field=models.CharField(choices=[('мужской', 'Мужской'), ('женский', 'Женский')], default='Все', max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
