# Generated by Django 4.2.3 on 2024-07-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='action',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
