# Generated by Django 4.2.3 on 2024-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_myself',
            field=models.TextField(default=''),
        ),
    ]
