# Generated by Django 4.2.3 on 2024-07-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_about_myself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='about_myself',
        ),
    ]
