# Generated by Django 4.2.3 on 2024-07-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_about_myself'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='confirmation_code',
        ),
    ]
