# Generated by Django 4.2.3 on 2024-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_promotion_userpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
