# Generated by Django 4.2.3 on 2024-07-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_promotion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
