# Generated by Django 5.0.4 on 2024-06-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
    ]
