# Generated by Django 4.2.3 on 2024-07-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
